'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SEMIFINALS_BRIONES_CUENCA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cartoon_Cookie__Photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cartoon Cookie_ Photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1_descrpt_2__1_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1_descrpt_2 (1)", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1_descrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1_descrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1_narrator_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1_narrator_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_1_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_1_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_1_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_1_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_1_pic_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_1_pic_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_1_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_1_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_10_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_10_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_10_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_10_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_10_descrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_10_descrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_10_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_10_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_10_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_10_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_10_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_10_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_1gif_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_1gif_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_1narrator() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_1narrator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_2_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_2_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_2_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_2_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_2_descrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_2_descrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_2_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_2_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_2_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_2_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_2_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_2_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_3_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_3_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_3descrpt1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_3descrpt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_4_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_4_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_4_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_4_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_4_descrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_4_descrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_4_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_4_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_4_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_4_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_4_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_4_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_5_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_5_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_5_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_5_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scene_5_descrpt_2__1_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scene_5_descrpt_2 (1)", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_5_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_5_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Scene_5_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scene_5_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_6_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_6_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_6_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_6_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_6_descrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_6_descrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_6_descrpt_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_6_descrpt_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_6_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_6_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_6_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_6_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_6_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_6_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_6_pic_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_6_pic_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_7_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_7_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_7_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_7_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_7_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_7_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_7_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_7_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_8_decrpt_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_8_decrpt_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_8_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_8_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_8_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_8_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_8_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_8_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_8_pic_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_8_pic_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_8descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_8descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_9_descrpt_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_9_descrpt_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property scene_9_descrpt_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("scene_9_descrpt_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_9_pic_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_9_pic_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene_9_pic_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene_9_pic_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scene3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scene3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Underwater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Underwater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property untilifoundyou() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("untilifoundyou", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
